### ISSUE TITLE
--daemonize fails to find certs

### ISSUE THREAD

**Issue by jandrieu** [pagekite/PyPagekite#39]
Pagekite works if I don't use --daemonize

```
./pagekite.py --optfile=./pagekite.rc --logfile=./log 
```

But if I call it with daemonize, I get errors about not able to find x X509 cert:

```
./pagekite.py --optfile=./pagekite.rc --logfile=./log --daemonize
```

Here is the error from the logfile:

```
ts=552e2968; t=2015-04-15T02:03:36; ll=43; err=Error in connect: Traceback (most recent call last):   File "<string>", line 464, in _BackEnd   File "<string>", line 324, in _Connect   File "<string>", line 1000, in connect   File "<string>", line 908, in __negotiatessl Error: [('system library', 'fopen', 'No such file or directory'), ('BIO routines', 'BIO_new_file', 'no such file'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]
ts=552e2968; t=2015-04-15T02:03:36; ll=44; err=Server response parsing failed: [('system library', 'fopen', 'No such file or directory'), ('BIO routines', 'BIO_new_file', 'no such file'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]; id=s0
ts=552e2968; t=2015-04-15T02:03:36; ll=45; eof=1; id=s0
```

In contrast, the log from the working run looks like:

```
started=./pagekite.py; ll=0; optfile_/home/joe/.pagekite.rc=ok; ts=552e29c7; argv=--optfile=./pagekite.rc --logfile=./log; optfile_./pagekite.rc=ok; platform=linux2; version=0.5.6d; t=2015-04-15T02:05:11; ca_certs=./pagekite.py
info=Collecting entropy for a secure secret.; ll=1; ts=552e29c7; t=2015-04-15T02:05:11
debug=Seeded signatures using /dev/urandom, hooray!; ll=2; ts=552e29c7; t=2015-04-15T02:05:11
debug=UiComm: Created; ll=3; ts=552e29c7; t=2015-04-15T02:05:11
ts=552e29c7; t=2015-04-15T02:05:11; ll=4; debug=Entering main epoll loop
```

**Comment by BjarniRunar** [comment]
Thank you for reporting this.

This would behave correctly if you were using absolute paths instead of relative; --daemonize changes the working directory of the process to /.

Sorry about the (very!) late reply; this is actually working as intended though.
